### ISSUE TITLE
Homebrew install failing

### ISSUE THREAD

**Issue by kartikkumar** [esa/pagmo#63]
Hi,

I just tried to install `pagmo` using the instructions given in the Wiki through the Homebrew Tap. I ran the following command:

```
brew install pagmo -v --with-boost
```

I get the following error:
```
 ==> Cloning http://git.code.sf.net/p/pagmo/code
git --git-dir /Library/Caches/Homebrew/pagmo--git/.git status -s
Updating /Library/Caches/Homebrew/pagmo--git
git config remote.origin.url http://git.code.sf.net/p/pagmo/code
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
git checkout -f master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/HEAD
HEAD is now at 648d059 Merge branch 'master' of ssh://git.code.sf.net/p/pagmo/code
git reset --hard origin/HEAD
HEAD is now at 648d059 Merge branch 'master' of ssh://git.code.sf.net/p/pagmo/code
git checkout-index -a -f --prefix=/private/tmp/pagmo-txmc/
Warning: Building bottled boost as you asked...
Error: private method `split' called for nil:NilClass
Please report this bug:
    https://github.com/Homebrew/homebrew/wiki/troubleshooting
/usr/local/Library/Taps/rmlopes-science/pagmo.rb:29:in `install'
/usr/local/Library/Taps/rmlopes-science/pagmo.rb:27:in `chdir'
/usr/local/Library/Taps/rmlopes-science/pagmo.rb:27:in `install'
/usr/local/Library/Homebrew/build.rb:174:in `install'
/usr/local/Library/Homebrew/formula.rb:267:in `brew'
/usr/local/Library/Homebrew/formula.rb:592:in `stage'
/usr/local/Library/Homebrew/resource.rb:62:in `unpack'
/usr/local/Library/Homebrew/extend/fileutils.rb:21:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:59:in `unpack'
/usr/local/Library/Homebrew/resource.rb:52:in `stage'
/usr/local/Library/Homebrew/formula.rb:590:in `stage'
/usr/local/Library/Homebrew/formula.rb:262:in `brew'
/usr/local/Library/Homebrew/build.rb:151:in `install'
/usr/local/Library/Homebrew/build.rb:45:in `main'
/usr/local/Library/Homebrew/build.rb:12
/usr/local/Library/Taps/rmlopes-science/pagmo.rb:37
```
I had a look in Homebrew `pagmo.rb` script and I think it might be failing because my `$PYTHONPATH` is not being loaded correctly.

Anyone know how to resolve this issue? 

I am running Mac OS X 10.8.5 and have Python 2.7.6 installed through Homebrew in addition to the system Python.

Thanks!

Kartik

**Comment by darioizzo** [comment]
Daniel did you not offer to make a homebrew recipe for PaGMO ? :)

**Comment by darioizzo** [comment]
Assume this now works ...
